services:
  - type: web
    name: swarm-multi-agent-system
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile - backend.main:app
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "1"
      # Database configuration
      - key: DATABASE_URL
        fromDatabase:
          name: swarm-multi-agent-db
          property: connectionString
      # Required API Keys (set these in Render dashboard)
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SUPERMEMORY_API_KEY
        sync: false
      - key: SUPERMEMORY_BASE_URL
        sync: false
      # Security
      - key: SECRET_KEY
        generateValue: true
      # Optional: Email Service
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_DOMAIN
        sync: false
      - key: MAILGUN_WEBHOOK_SIGNING_KEY
        sync: false

databases:
  - name: swarm-multi-agent-db
    databaseName: swarm_multi_agent
    user: swarm_user
    region: oregon
    plan: free
