services:
  - type: web
    name: swarm-multi-agent-system
    env: python
    region: oregon
    plan: starter
    # Setup script for debugging and verification
    preDeployCommand: |
      chmod +x setup.sh
      ./setup.sh
    # Build command with enhanced dependency management
    buildCommand: |
      echo "🔧 Starting build process..."
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "📦 Verifying critical packages..."
      pip list | grep -E "(flask|gunicorn|psycopg2|requests|pydantic)"
      echo "✅ Build completed successfully!"
    # Start command with enhanced logging and timeout
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile - --log-level info app:app
    # Health check endpoint
    healthCheckPath: /api/health
    # Auto-deploy on git push
    autoDeploy: true
    # Environment variables
    envVars:
      # Python configuration (updated to 3.13 for compatibility)
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      
      # Database configuration
      - key: DATABASE_URL
        fromDatabase:
          name: swarm-multi-agent-db
          property: connectionString
      
      # Required API Keys (set these in Render dashboard)
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SUPERMEMORY_API_KEY
        sync: false
      - key: SUPERMEMORY_BASE_URL
        sync: false
      
      # Security
      - key: SECRET_KEY
        generateValue: true
      
      # Application configuration
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
      - key: DEBUG
        value: "false"
      
      # MCP Filesystem configuration
      - key: MCP_WORKSPACE_PATH
        value: "/tmp/swarm_workspace"
      
      # Optional: Email Service
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_DOMAIN
        sync: false
      - key: MAILGUN_WEBHOOK_SIGNING_KEY
        sync: false

databases:
  - name: swarm-multi-agent-db
    databaseName: swarm_multi_agent
    user: swarm_user
    region: oregon
    plan: free
