# 🚀 Render Configuration for Swarm Multi-Agent System v3.0

services:
  - type: web
    name: swarm-multi-agent-system-v3
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r config/requirements.txt
    startCommand: python backend/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true

