services:
  - type: web
    name: swarm-agents-web
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      echo "🔧 Starting CLEAN build process..."
      echo "Current directory: $(pwd)"
      
      echo "📦 Installing minimal Python dependencies..."
      pip install --upgrade pip
      pip install flask flask-cors flask-socketio eventlet requests gunicorn python-socketio
      
      echo "🔨 Building React frontend..."
      cd frontend
      npm install
      npm run build
      echo "Frontend build complete"
      ls -la dist/
      ls -la dist/assets/
      cd ..
      
      echo "✅ Build completed successfully!"
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT --timeout 120 app_clean:application
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: "10000"

# Removed database for now - can add back later if needed
