services:
  - type: web
    name: swarm-agents-web
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      echo "🔧 Starting CLEAN build process..."
      echo "Current directory: $(pwd)"
      
      echo "📦 Installing minimal Python dependencies..."
      pip install --upgrade pip
      pip install -r requirements_clean.txt
      
      echo "🔨 Building React frontend..."
      cd frontend
      npm install
      npm run build
      echo "Frontend build complete"
      ls -la dist/
      ls -la dist/assets/
      cd ..
      
      echo "✅ Build completed successfully!"
    # Start command with enhanced logging and timeout
    startCommand: gunicorn --worker-class eventlet --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --access-logfile - --error-logfile - --log-level info app_clean:application
    # Health check endpoint
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: "10000"

# Removed database for now - can add back later if needed
